#!/usr/bin/bash

awk '/Bubble area = / {print $4}' $1 > isoBubbleArea.dat
awk '/Bubble centre = / {print $4,$5,$6}' $1 > isoBubbleCentre.dat

sed -i 's/(//g' isoBubbleCentre.dat 
sed -i 's/)//g' isoBubbleCentre.dat 

paste isoBubbleArea.dat isoBubbleCentre.dat > isoBubble.dat

rm -rf isoBubbleArea.dat
rm -rf isoBubbleCentre.dat 
