#!/bin/sh

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export OFBOOK_CODE_PROJECT_DIR=${DIR%%/etc*}

export OFBOOK_CODE_SRC=$OFBOOK_CODE_PROJECT_DIR/src

export PATH=$OFBOOK_CODE_PROJECT_DIR/src/scripts:$PATH
