#!/bin/sh

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export PRIMER_EXAMPLES=${DIR%%/etc*}

export PRIMER_EXAMPLES_SRC=$PRIMER_EXAMPLES/src

export PATH=$PRIMER_EXAMPLES_SRC/scripts:$PATH
