#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory


wmakeLnInclude -f .
wmake libso bubbleCalc
wmake libso primerBoundaryConditions 
wmake libso ofBookTransportModels
wmake libso ofBookFunctionObjects
wmake libso ofBookDynamicFvMesh 
